### ISSUE TITLE
Basic Questions on Ordered Accumulation, Prerequisites, Exceptions + Checkpoints

### ISSUE THREAD

**Issue by sourabhniyogi** [gavofyork/graypaper#129]
*Background*. Lets say we wish to compute $C[n + 1] = A[n] + B[n] + C[n]$ (some kind of recurrence relationship, lets say Fibonacci, Tribonnaci, and Quadranocci in a toy example, all of $A$, $B$, $C$ trying to write their value into service storage of key 0) using the `refine` work results of services $A[n]$, $B[n]$, $C[n]$ coming into `accumulate`.  We would like service $C$ to be able to `read` the results of $A, B, C$ and `write` out $C[n+1]$ to the service storage of $C$ in $C$'s `accumulate` code.    

Questions:

1. If we have a _single_ work package $p$ with 3 work items from service $A$, $B$, $C$ (with no prerequisites), there is **NO** way to have $C$'s `write` _guaranteed_ to happen **AFTER** $A$ and $B$. This is because $\Delta_{+}$ will initialize _parallelized_ execution of $\Delta_1$ for all 3 services through $\Delta_*$.  Can you confirm this?

2. If we have _three_ work packages $p_A, p_B, p_C$ with 1 work item each ($p_A$ with `refine` work results from service A, $p_B$ from service $B$, $p_C$ from $C$), we **CAN** have C's `write` happen after A and B, by specifying BOTH $p_A$ and $p_B$ as _prerequisite_ work packages of $p_C$.  This SET of TWO prereqs was not possible until GP 0.4.5 supporting a _set_ of prerequisites.  Can you confirm this?

3. If (2) is correct, for the $C[n + 1] = A[n] + B[n] + C[n]$ `write` to happen _at the same time slot_ for some `n`, then another to happen within 2 timeslots for the next `n`, we **REQUIRE** _three_ cores for _three_ work packages, one core for each work package.  In a tiny $V=6,C=2$ test configuration, we CANNOT achieve this, but in a small configuration with $V=9,C=3$, we CAN.  Can you confirm this?

4. Actually, the answer to (3) is more nuanced!   Because we could actually solve this ordered accumulation $C[n + 1] = A[n] + B[n] + C[n]$ with only TWO cores working on TWO packages -- one package $p_{A,B}$ with 2 work items using services $A$ and $B$ and then another package $p_C$ with ONE prerequisite: $p_{A,B}$.  Then with a tiny $V=6,C=2$ test configuration, we CAN achieve the `read` of $C$ based on the `write`s of $A$ and $B$ all in one `accumulate` at the same time slot.  Can you confirm this?

5. With a tiny testnet of $V=6,C=2$, it IS possible test (4) using $\Delta_+$ with $i$ splitting ${\bf w}$ into two pieces that test $\Delta_*$ and the tail recursion of $\Delta_+$.  To observe $N$ calls to $\Delta_+$, you need $N-1$ cores though and need to figure out how to manage $g$ in $N$ splits.  Can you confirm this? 

    [If this is wrong, please advise how we should test $\Delta_+$]

6. Setting aside gas limits for a while (because at present anyway every operation is gas 1 or so, and the accumulation limit is 5-6 orders of magnitude higher) we can have 25 cores working on 25 work packages like this all in one `accumulate` of `Z[n+1]`, with each work package having 2 prerequisites (except for $p_{A,B}$ which have none):

  * $C[n + 1] = A[n] + B[n] + C[n]$ ($p_C$ depending on $p_{A,B}$ using 2 cores)
  * $D[n + 1] = B[n] + C[n+1] + D[n]$       ($p_D$ depending on $p_{A,B}$ and $p_{C}$ using 1 more core for $D$)
  * $E[n + 1] = C[n+1] + D[n+1] + E[n]$     ($p_E$ depending on $p_{C}$ and $p_{D}$ using 1 more core for $E$)
  * $F[n + 1] = D[n+1] + E[n+1] + F[n]$     ($p_F$ depending on $p_{D}$ and $p_{E}$ using 1 more core for $F$)
  * ... and so on until ...
  * $Z[n + 1] = X[n+1] + Y[n+1] + Z[n]$     ($p_Z$ depending on $p_{X}$ and $p_{Y}$ using 1 more core for $Z$)

  Assuming all 25 cores can complete their 25 refines and get 25 work reports guaranteed and assured in a medium configuration ($V=120,C=40$), we can have the entire ordered accumulation done in ONE timeslot.  Can you confirm this?

**Comment by sourabhniyogi** [comment]
Thank you for confirming + clarifying.  We'll work on our understanding of what happens when "out of gas" situations and follow up soon. 

Generic interrelated questions concerning JAM messaging services using Ordered Accumulation + Prerequisites:
1. How should a non-Polkadot messaging JAM service (not passing around XCM/XCMP related, but generic blobs) use prerequisites, if at all?  We want the messaging service to be accumulated after all other services to get their "outgoing message", which could be done with Ordered Accumulation.   But it seems weird for a messaging service to look around for workpackage hashes of its message-sending services when it appears to need something like a "HRMP channel"/"service X can use this service".   In addition, there is a 8 prereq limit.   GP section 21  "Synchronous calls between services in accumulate." (which could be used to address non-Polkadot messaging systematically instead of using prereq) but surely this would destroy the beauty of parallelized $\Delta_*$ and the simplicity of the prereq model.     Is there some "Transfer" way of solving this messaging problem that is basically the last accumulate?
2. Between 0.3 and 0.4.x you added $\chi_{\bf g}$ and adjusted `empower` -- maybe messaging services could be "the first" and/or "the last" accumulate in ${\bf W}^*$  to handle incoming/outgoing messages rather than (2), but how does some service operator get into $\chi_{\bf g}$ "always accumulate" via `empower` ?

If the above is not appropriate to ask, will close this issue.  Thank you!

**Comment by gavofyork** [comment]
1. The 8 dependencies limit may be lifted somewhat after we do performance testing. It's currently selected to avoid the possibility of introducing any substantial cost to block execution. It might easily be that we can afford to lift this by an order of magnitude or two.

Overall service composition is left as "an exercise for the reader". There are a few ways that composition could happen.

a. Synchronous composition between services in Refine-stage by co-scheduling work-packages and some signalling within Accumulate that the entangled work-items are both integrated into the final state as expected.
b. Asynchronous composition between services in Refine-stage through setting dependency-requirements together with signalling in Accumulate to ensure that the dependent work-item is integrated into the final state as expected.
c. Asynchronous composition between services in Accumulate-stage through `transfer` and perhaps service-storage. No additional signalling necessary.

These have not been fully analysed and are certainly not prototyped yet, so I can't really go into too much detail. JAM may yet be tweaked in order to further facilitate cross-service composition. One possible tweak would be to provide a facility for registering a properly integrated work-item rather than leaving it to finding a convention on the usage of `transfer` or `storage`.

I'd be interested to hear about the results of your experiments in this area.

**Comment by sourabhniyogi** [comment]
1.  Alright I understand (a)+(b) but not (c), so I'll attempt to understand what that entails.   I'll take on exercise (c), ok!
2.  Got it.  You're right, "direct service-to-service messaging" is best.   Was (mindlessly) thinking we want a blob messaging service because of the "butterfly argument" (that a messaging service with O(N) channels is better than O(N^2) service-to-service) but that doesn't make sense because work reports can send blobs and N services will fully "send messages" via `write` operations, and can "receive messages" via `read` operations.  Each just need some signals to where to find each others mailboxes and there is no need for O(N) prereqs.
===

#### Basic Questions on Ordered Accumulation, Exceptions and checkpoints:

**Background.**    When a service hits "out of gas"  $\infty$ or "panic" $\Lightning$ coming out of $\Delta_1$ 's $\Psi_A$ EXCEPTIONAL context ${\bf y}$ instead of ${\bf x}$ is returned instead.   Don't panic though, because the `checkpoint` host function enables `accumulate` service code to still succeed by having ${\bf y}$ get a copy of ${\bf x}$.   What this means in practice is that if there is iteration in loops going on in `accumulate` (say, putting some validated blocks into chains, issuing a lot of solicits + forgets, processing some large number of messages, whatever), service authors can `checkpoint` in their iteration loops and pick up where they left off. 

1. Services authors with services taking advantage of `checkpoint` CAN hit EXCEPTIONS (of $\infty$) and kamikaze-ing in this way _is just fine.   [Yes, there is `gas` for them to NOT kamikaze].  Then you have :
(a) NO Beefy root $b \in \mathbb{H}?$ with ${\bf y}$ [here](https://graypaper.fluffylabs.dev/#/293bf5a/2bce022bce02)
(b) NO way for dependent services to even know about the "out of gas" 
Can you confirm this?  Is (a) a feature or a bug?  Is (b) a feature or a bug?

2. A service accumulation having an "exception" (of $\infinty$ or $\Lightning$) and getting ${\bf y}$ in $\Delta_1$ does NOT affect the accumulation behavior of other services.  For example, if work package $p_{C}$ (causing service $C$ to `accumulate`) has a prereq of $p_{A,B}$ (causing service $A$ and $B$ to `accumulate`) but say `accumulate` of kamikaze $A$ has an "exception" (and thus, as per 1(a) an empty Beefy root), then and as per 1(b) (I think) there is no way for service $C$ to check if $A$ hit the "exception" _except_ by "peeking" into some breadcumb signals left by $A$, e.g. it in its `checkpoint` sitting in $A$ service storage.  

Can you confirm my understanding?  What did I get wrong?

**Comment by sourabhniyogi** [comment]
**Question on Accumulation of Privileged Services:**

As $\Delta_+$ may result in multiple calls to $\Delta_*$ [here](https://graypaper.fluffylabs.dev/#/364735a/179700179700), what is preventing more than 1 call to the $\Delta_1$ of { m, a, v } [here](https://graypaper.fluffylabs.dev/#/364735a/178c0117aa01)?  

Probably a pedantic issue, but we want just 1 call to $\Delta_1$ for each of { m, a, v } here, right?

**Comment by gavofyork** [comment]
> **Question on Accumulation of Privileged Services:**
> 
> As Δ + may result in multiple calls to Δ ∗ [here](https://graypaper.fluffylabs.dev/#/364735a/179700179700), what is preventing more than 1 call to the Δ 1 of { m, a, v } [here](https://graypaper.fluffylabs.dev/#/364735a/178c0117aa01)?
> 
> Probably a pedantic issue, but we want just 1 call to Δ 1 for each of { m, a, v } here, right?

Mathematical functions do not necessarily translate to real function calls. In this case, there's only a requirement to do a function call for the case of service ID $m$ (or $a$, or $v$) if that service has any allotted gas. If said service does, then we want to accumulate it and alter `x'` (or `i'`/'`q'`) accordingly.

**Comment by gavofyork** [comment]
> 1. Can you confirm this?  Is (a) a feature or a bug?  Is (b) a feature or a bug?

a. Yes, this isn't super sensible and might be something which we want to tweak (perhaps to a host-call for returning a BEEFY hash).
b. This is as expected.

**Comment by gavofyork** [comment]
> 2\. there is no way for service $C$ to check if $A$ hit the "exception" _except_ by "peeking" into some breadcrumb

Correct. This is generally true. e.g. $pA$ may be valid $per se$, but not be accumulatable according to the state of $A$ when it comes to being accumulated. $pC$ might be able to assume that service $A$'s accumulate code has seen $pA$, but (depending entirely on service $A$'s Accumulate code) it cannot generally assume that $A$ has done any particular thing with it.

For totally trivial services where accumulation has no conditionals and is infallible, then there's no need for any extra signalling between service Accumulation cpde.

However in general entangled services will need to signal across Accumulate (through storage peeking and/or memo transfers) in order to ensure that "the right thing" happened in Accumulate.

**Comment by gavofyork** [comment]
While the effects of accumulation are a higher level, service-dependent concept not to be convered in the JAM protocol (at least not yet), it is quite a useful concept to be able to name. An example would be in the parachains service (_CoreChains_), where a WP might imply a block is valid and finalisable yet when it gets to Accumulate, some other WP has since been accumulated which has finalized a block which is mutually exclusive with that of the first WP.

In general discourse I call this application of the effects of Refine into the overall service state *Integration*. Whereas Accumulation is guaranteed to happen, potentially in some particular order of WPs, the service code alone decides if, how and when Integration will happen. And for cross-service communication (or, more technically, Work-Item entanglement) it is Integration which it is important that happens in a synchronised fashion, not merely Accumulation.
